"""Add service_type and desired_date to orders

Revision ID: df77c0cdec34
Revises: 9fde853a345c
Create Date: 2026-03-06 19:19:11.688436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df77c0cdec34'
down_revision: Union[str, Sequence[str], None] = '9fde853a345c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('service_type', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('desired_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'desired_date')
    op.drop_column('orders', 'service_type')
    # ### end Alembic commands ###
